import type { NextPage } from 'next'
import Head from 'next/head'
import { GridMap } from '../components/GridMap'
import styles from '../styles/Home.module.css'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'

const queryClient = new QueryClient()

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
				<QueryClientProvider client={queryClient}>
					<GridMap />
				</QueryClientProvider>
      </main>
    </div>
  )
}

export default Home
